services:
  db:
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wp_zume5
    expose:
      - 3306
      - 33060
  wordpress:
    container_name: zume-training-xdbg
    build:
      dockerfile: Dockerfile
      context: ./xdebug
    volumes:
      - wp_data:/var/www/html
      - ./wordpress:/var/www/html
      - ./wordpress/.htaccess:/var/www/html/.htaccess
    depends_on:
      - db
    user: 33:1000
    ports:
      - 5000:8000
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: somewordpress
      WORDPRESS_DB_NAME: wp_zume5
      WORDPRESS_DB_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'SCRIPT_DEBUG', false );
        define( 'WP_ALLOW_MULTISITE', true );
        define( 'MULTISITE', true );
        define( 'SUBDOMAIN_INSTALL', false );
        define( 'DOMAIN_CURRENT_SITE', 'zume5.test' );
        define( 'PATH_CURRENT_SITE', '/' );
        define( 'SITE_ID_CURRENT_SITE', 1 );
        define( 'BLOG_ID_CURRENT_SITE', 1 );
        define( 'WP_MEMORY_LIMIT', '512M' );
        error_reporting(E_ALL & ~E_WARNING & ~E_DEPRECATED & ~E_USER_DEPRECATED & ~E_NOTICE);
      ## Host for my house ##
      XDEBUG_CONFIG: client_host=192.168.10.23 log=/tmp/xdebug.log start_with_request=yes debug_level=10
      ## Host for Brian's house ##
      #XDEBUG_CONFIG: client_host=192.168.0.34 log=/tmp/xdebug.log start_with_request=yes debug_level=10
      ## Host for Watford house ##
      #XDEBUG_CONFIG: client_host=192.168.0.75 log=/tmp/xdebug.log start_with_request=yes debug_level=10
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 5025:8025 # web ui
  wp-cli:
    image: wordpress:cli-php8.2
    volumes:
      - wp_data:/var/www/html
      - ./wordpress:/var/www/html
      - ./wordpress/.htaccess:/var/www/html/.htaccess
    depends_on:
      - wordpress
    user: xfs
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: somewordpress
      WORDPRESS_DB_NAME: wp_zume5
    command: /bin/sh -c "tail -f /dev/null"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 5081:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=somewordpress
volumes:
  db_data:
  wp_data:
